// <auto-generated />
using ApiPrueba130426.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPrueba130426.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415235449_llenadodetabla")]
    partial class llenadodetabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("ApiPrueba130426.Models.Tabla1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tabla1s");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Tercero"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
