// <auto-generated />
using ApiPrueba130426.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPrueba130426.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("ApiPrueba130426.Models.Tabla1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tabla1");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Tercero"
                        });
                });

            modelBuilder.Entity("ApiPrueba130426.Models.Tabla2", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroT")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Tabla2");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Apellido = "Apellido1",
                            NumeroT = 100
                        },
                        new
                        {
                            id = 2,
                            Apellido = "Apellido2",
                            NumeroT = 200
                        },
                        new
                        {
                            id = 3,
                            Apellido = "Apellido3",
                            NumeroT = 300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
